sudo: required
dist: trusty

language: c
compiler:
  - gcc


before_script:
    - sudo apt-get update -qq || true
    - sudo apt-get install -y lib32ncurses5  make bc gawk
    - sudo apt-get install realpath
    - sudo pip install cpp-coveralls
    - gcc --version

install:
    - cd ./project/realtek_ameba1_va0_example/GCC-RELEASE
    - make clean;make
