sudo: required
dist: trusty

language: c
compiler:
  - gcc


  before_script:
  # Extra CPython versions
  #  - sudo add-apt-repository -y ppa:fkrull/deadsnakes
  # Extra gcc versions
  #  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
    - sudo add-apt-repository -y ppa:terry.guo/gcc-arm-embedded
    - sudo dpkg --add-architecture i386
    - sudo apt-get update -qq || true
    - sudo apt-get install -y lib32ncurses5  make bc gawk
  #  - sudo apt-get install -y python3 gcc-multilib pkg-config libffi-dev libffi-dev:i386 qemu-system mingw32
  #  - sudo apt-get install -y --force-yes gcc-arm-none-eabi
    # For teensy build
    - sudo apt-get install realpath
    # For coverage testing
    - sudo pip install cpp-coveralls
    - gcc --version
    - arm-none-eabi-gcc --version
    - python3 --version

install:
    - cd ./project/realtek_ameba1_va0_example/GCC-RELEASE
    - make clean;make
